# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18PHZV0-uxrMDYDqhjPWJV1mCzr4qhlMO
"""

# app.py

import streamlit as st
from gensim.models import KeyedVectors
import gensim.downloader as api
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Title
st.title("🔤 Word2Vec Analogy Explorer")
st.markdown("Try analogies like **king - man + woman = ?**")

# Load model (cache so it's not reloaded every time)
@st.cache_resource
def load_model():
    return api.load("glove-wiki-gigaword-50")

model = load_model()

# Input widgets
word_a = st.text_input("Word A", "king")
word_b = st.text_input("Word B", "man")
word_c = st.text_input("Word C", "woman")
topn = st.slider("Top N Results", 1, 10, 5)

# Compute button
if st.button("Compute Analogy"):
    a, b_, c = word_a.lower(), word_b.lower(), word_c.lower()
    try:
        result = model.most_similar(positive=[a, c], negative=[b_], topn=topn)
        st.subheader(f"Analogy: `{a} - {b_} + {c} ≈ ?`")
        for word, score in result:
            st.write(f"**{word}**: {score:.4f}")

        # PCA Plot
        words_to_plot = [a, b_, c, result[0][0]]
        vectors = [model[w] for w in words_to_plot]

        pca = PCA(n_components=2)
        vec_2d = pca.fit_transform(vectors)

        fig, ax = plt.subplots(figsize=(8, 6))
        for i, word in enumerate(words_to_plot):
            ax.scatter(*vec_2d[i], label=word, s=100)
            ax.text(*vec_2d[i], word, fontsize=12)
        ax.set_title(f'PCA Projection: {a} - {b_} + {c} ≈ {result[0][0]}')
        ax.grid(True)
        ax.legend()
        st.pyplot(fig)

    except KeyError as e:
        st.error(f"Word not in vocabulary: {e}")

