# -*- coding: utf-8 -*-
"""final -app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10VHmU2S-GvFS05SMHhlxmJu8TD4XVGdL
"""

import streamlit as st
from gensim.models import KeyedVectors
import gensim.downloader as api
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt

# Title
st.title("🔤 Word2Vec Analogy Explorer")
st.markdown("Explore analogies like **king - man + woman ≈ ?** using pre-trained Word2Vec!")

# Load pre-trained Word2Vec model
@st.cache_resource
def load_model():
    return api.load("glove-wiki-gigaword-50")  # or try "glove-twitter-25" for faster load

model = load_model()

# Predefined analogy examples
examples = {
    "king - man + woman ≈ queen": ("king", "man", "woman"),
    "paris - france + germany ≈ berlin": ("paris", "france", "germany"),
    "walking - walk + swimming ≈ swim": ("walking", "walk", "swimming"),
    "banana - fruit + carrot ≈ vegetable": ("banana", "fruit", "carrot"),
    "boy - girl + prince ≈ princess": ("boy", "girl", "prince"),
    "football - sport + chess ≈ game": ("football", "sport", "chess"),
}

# Sidebar: Pick a fun example
st.sidebar.header("🎲 Try These Fun Analogies")
selected_example = st.sidebar.selectbox("Pick one:", [""] + list(examples.keys()))

# Input fields
if selected_example:
    word_a, word_b, word_c = examples[selected_example]
    st.success(f"Example loaded: {selected_example}")
else:
    word_a = st.text_input("Word A", "king")
    word_b = st.text_input("Word B", "man")
    word_c = st.text_input("Word C", "woman")

topn = st.slider("Top N Similar Words", min_value=1, max_value=10, value=5)

# Button
if st.button("🔍 Compute Analogy"):
    a, b_, c = word_a.lower(), word_b.lower(), word_c.lower()

    try:
        result = model.most_similar(positive=[a, c], negative=[b_], topn=topn)
        st.subheader(f"🔁 Analogy: `{a} - {b_} + {c} ≈ ?`")
        for word, score in result:
            st.write(f"**{word}** — similarity: {score:.4f}")

        # PCA Visualization
        words_to_plot = [a, b_, c, result[0][0]]
        vectors = [model[w] for w in words_to_plot]
        pca = PCA(n_components=2)
        vec_2d = pca.fit_transform(vectors)

        fig, ax = plt.subplots(figsize=(8, 6))
        for i, word in enumerate(words_to_plot):
            ax.scatter(*vec_2d[i], s=100)
            ax.text(*vec_2d[i], word, fontsize=12)
        ax.set_title(f"PCA Projection: {a} - {b_} + {c} ≈ {result[0][0]}")
        ax.grid(True)
        st.pyplot(fig)

    except KeyError as e:
        st.error(f"❌ Word not in vocabulary: {e}")

